services:
  - type: web
    name: fiuggigram
    env: python
    region: frankfurt
    buildCommand: "pip install flask"
    startCommand: "python app.py"
    envVars:
      - key: PORT
        value: 10000
